# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: AWS UI and Accessibility Testing

on: 
  workflow_dispatch:
  

env:
  UI_TEST_URL : ${{ secrets.AWS_UI_URL }}
  LOGIN_CRED_EMAIL : ${{ secrets.LOGIN_CRED_EMAIL }}
  LOGIN_CRED_PWD : ${{ secrets.LOGIN_CRED_PWD }}

jobs:
      
  ui-accessibility-testing:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    # Only checks out the head branch of the PR (the branch the PR is being create about). This is to ensure compatibility with API repository.
    - name: Checkout UI
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run:  npm ci

    - name: UI Tests
      run: npm run test-ui
  
    - name: Accessibility Tests
      run: npm run test-accessibility

